# =========================

SEGMENTATION: false
DEBUG: false
DEBUG_STEP: 0
dataset_name: "Dataset003_CoronaryMed"
img_ext: ".nii.gz"

fold: 5

# gnn_model prediction settings
knn_k: 24
knn_radius_mm: 12.0
edge_prob_thresh: 0.35

# Component cropping
top_k_components: 10
pad_mm: [0,0,0]
min_size_mm: [12.0, 12.0, 12.0]

# FMM/target selection
max_targets_per_comp: 25
min_target_sep_mm: 9.0
spur_len_min_mm: 9.0
prob_min: 0.6
prob_exp: 9

# Tracer limits
MAX_STEPS_PER_COMPONENT: 220

# --- Assembly
WEIGHTED_ASSEMBLY: true
WEIGHT_TYPE: radius

# --- ROI crop sizing ---
VOLUME_SIZE_RATIO: 16.0
MAGN_RADIUS: 1.2
MIN_RES: 24

# --- Radii handling at step proposals ---
MIN_RADIUS: 0.4              # mm; lower clamp on fused radius
ADD_RADIUS: 0.0              # mm; bias added to proposed step radius

# --- Cone-based candidate generation (legacy/local) ---
NUM_DIRS: 48
ANGLE_ALLOW_DEG: 180.0
RAY_LEN_MM: 16.0
STEP_MM: null                # null for adaptive
TUBE_SIGMA_MM: 0.3           # for image evidence

# skeleton based scoring
BIN_THR: 0.5
OPEN_RADIUS_VOX: 1
CLOSE_RADIUS_VOX: 0
SKEL_SUBSAMPLE_MM: 1.5
SKEL_NHOOD_MM: 2.5
MAX_CAND_TOTAL: 512

# Scoring weights
W_IMG: 0.5
W_EDGE: 0.5
W_NODE_CL: 0.5
W_VOR: 0.2
W_ANGLE: 0.2
PROB_GAMMA: 0.5

GRAPH_TAU_MM: 3.0            # leash to Gvol (distance decay)
CENTERLINE_TAU_MM: 3.0       # leash to Gcent (distance decay)
EDGE_BRIDGE_TAU_MM: 10.0     # when no direct edge, soft bridge via distance
KEY_NODE_CL: node_prob_cl    # attribute name for Gcent node prior (fallbacks to node_prob)


EDGE_KHOP_MAX: 3
EDGE_FWD_COS_THR: 0.3
EDGE_AGG: "min"
EDGE_PROB_KEY: "edge_prob"
EDGE_FALLBACK_PROB: 0.5
W_NEAR_CL: 0.2

# --- Voronoi within current ROI (optional, soft guidance only) ---
VOR_ENABLE: true
VOR_STREAK_LEN: 5
VOR_CELL_COVER_THR: 0.7
VOR_CELL_MIN_NODES: 3

#For local auto reseed
CROSS_VOR_K: 16

# Per-cell coverage gates
CELL_STALL_MIN_NEW: 2
CELL_STALL_MAX_STEPS: 3
CELL_COVERAGE_STOP: 1

# Global coverage
STALL_MIN_NEW_COVER: 3
STALL_MAX_STEPS: 7
RESEED_MIN_SEP_MM: 3.0
RESEED_POLICY: farthest
RESEED_ALPHA_PROB: 0.4
RESEED_BETA_RADIUS: 0.8
RESEED_GAMMA_DIST: 0.4
RESEED_MIN_DEGREE: 2
RESEED_TARGETS_FIRST: false

# --- Global stop conditions ---
COVERAGE_STOP: 0.95
STOP_WHEN_ALL_TARGETS: false
MAX_RESEED_NO_GAIN: 100

W_NEAR_VOL: 0.3
W_RADIUS: 0.2



# score gate
SCORE_MIN: 0.35
